#**1. Business Understanding**
##**1.1 Project overview**
This project uses the World Health Organization (WHO) Global Health Observatory dataset to examine trends in the estimated number of people living with HIV across countries from 2000 to 2023.
The analysis focuses on two questions:
1. *Which countries collectively account for approximately 75% of the global reported HIV burden, and how has their burden changed over time?*
2. *Which countries within the WHO African Region collectively account for approximately 75% of the region's reported HIV burden, and what trends do they exhibit?*

The analysis will use data preparation, cleaning, exploratory data analysis (EDA), cumulative burden calculations, and time-series visualizations to produce insights useful for public health planning and resource allocation.

**Important distinction**: The dataset measures the estimated number of people living with HIV, not the number of new HIV infections. These figures reflect the existing burden of HIV, including people who may be receiving treatment.

##**1.2 Objective**
###**1.2.1 Primary objective**
To analyze and visualize the distribution and trends of people living with HIV in countries that collectively account for approximately 75% of the reported global burden and the reported burden within the WHO African Region.

####**1.2.2 Specific objectives**
1. Identify high-burden countries: Rank countries by their estimated number of people living with HIV in 2023 and select countries accounting for approximately 75% of the reported total.
2. Analyze global trends: Examine how the estimated number of people living with HIV has changed in the selected countries between 2000 and 2023.
3. Analyze African regional trends: Identify the countries accounting for approximately 75% of the reported African regional burden and compare their trends.
4. Identify public health priorities: Highlight countries with persistently high or increasing numbers of people living with HIV.
5. Support evidence-based decisions: Translate the findings into insights that can inform HIV prevention, treatment, testing, and healthcare resource planning.

##**1.3 Business Value**
This analysis provides actionable insights into the distribution and long-term trends of the HIV burden within the WHO African Region. By identifying countries that collectively account for at least 75% of people living with HIV, the analysis supports evidence-based resource allocation, targeted intervention planning, policy development, and monitoring of public health progress. The findings can help governments, healthcare providers, and funding organizations prioritize services and plan for treatment needs, ultimately supporting more efficient use of limited healthcare resources and improved HIV program outcomes.

**Expected value**: Better targeting of limited public health resources and clearer monitoring of HIV burden over time. The analysis can inform decisions, but it does not independently establish which interventions caused changes in HIV trends.

##**1.4 Success Metrics**

Success should be measured using both data-quality metrics and analytical-output metrics.

| **Metric** | **Proposed success criterion** |
|---|---|
| Data completeness | Quantify missing estimates by country and year, and document their impact on the analysis. |
| Data integrity | Zero duplicate country-year records after validation. |
| Numeric accuracy | Confirm that estimates are parsed correctly from the WHO's formatted values. |
| Burden coverage | Selected countries account for at least 75% of the available reported burden in the reference year, where feasible. |
| Visualization completeness | Produce two readable, labeled time-series visualizations. |
| Analytical reproducibility | Use a documented, repeatable method for ranking countries and calculating cumulative shares. |
| Insight generation | Identify major high-burden countries and notable increases, decreases, or stable trends. |
| Decision usefulness | Present findings that can inform practical public health planning questions. |

**A key qualification is necessary**: because some countries have missing estimates, the 75% threshold must be calculated against the sum of reported estimates, not assumed to represent 75% of the true worldwide total.

#**2. Data Understanding**
The dataset, *HIV data 2000-2023.csv*, contains country-level WHO estimates of people living with HIV.

## 2.1 **Dataset Overview**

| Metric | Value |
| --- | ---: |
| Total records | 1,552 |
| Countries / locations | 194 |
| Time span | 2000–2023 |
| Recorded years | 8 |


The recorded years are 2000, 2005, 2010, 2015, and 2020–2023. The dataset does not provide annual observations for every year in the full period.

The recorded years are 2000, 2005, 2010, 2015, and 2020–2023. The dataset does not provide annual observations for every year in the full period.

##2.2 **Variable descriptions**

| Variable | Description | Analytical use |
| --- | --- | --- |
| IndicatorCode | WHO indicator identifier | Verify the indicator being analyzed |
| Indicator | Description of the HIV indicator | Confirm the outcome of interest |
| ValueType | Type of reported value | Understand the format of the data |
| ParentLocationCode | WHO region code | Regional filtering |
| ParentLocation | WHO region name | Identify the African Region and other regions |
| Location type | Geographic entity type | Restrict analysis to countries |
| SpatialDimValueCode | Country or location code | Identify and validate locations |
| Location | Country name | Ranking and trend analysis |
| Period type | Time-period classification | Confirm yearly observations |
| Period | Observation year | Time-series analysis |
| Value | Estimate, often with lower and upper uncertainty bounds | Outcome variable |

The numerical estimates are contained within the Value column, for example:
320 000 [280 000 - 380 000]
The central estimate is 320,000 people living with HIV, with a reported uncertainty range from 280,000 to 380,000.

##2.3 **Initial data-quality findings**
- There are 1,552 records representing 194 locations across eight recorded years.
- The data contains 394 records explicitly labeled No data.
- There are no duplicate country-year records in the initial dataset.
- The 2023 data contains estimates for 143 of the 194 locations, leaving 51 without a numeric estimate.
- The dataset contains reported estimates and uncertainty intervals, so the central estimates should not be interpreted as exact counts.

# Data Preperation
## Data Cleaning
This includes
 * loading the dataset
 * exploring our data using methods like(df.head,df.describe,df.info)to get a sense of the data structure,data types and summary statistics
 * manipulating column names for better readability
 * dropping unnecessary columns
 * identify missing values using df.isnull().sum() then fill the missing values appropriately if any,or drop them
 * identify duplicates(df.duplicated() and remove them using df.drop_duplicated
 * check the data types if they are appropriate for each column if not correct them
 * check and handle outliers appropriately
 * create new features
 * do final checks then save the cleaned data

## **Load the dataset**

In [11]:
#import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import warnings
warnings.filterwarnings('ignore')

In [13]:
#import file
from google.colab import files
upload = files.upload()

In [14]:
#list all files in the current directory
os.listdir()

['.config', 'HIV data 2000-2023.csv', 'sample_data']

In [15]:
#load dataset
df=pd.read_csv('HIV data 2000-2023.csv', encoding='latin-1')

## **Explore the data**

In [16]:
#view the dataset
df.head()

,IndicatorCode,Indicator,ValueType,ParentLocationCode,ParentLocation,Location type,SpatialDimValueCode,Location,Period type,Period,Value
0,HIV_0000000001,Estimated number of people (all ages) living w...,numeric,AFR,Africa,Country,AGO,Angola,Year,2023,320 000 [280 000 - 380 000]
1,HIV_0000000001,Estimated number of people (all ages) living w...,numeric,AFR,Africa,Country,AGO,Angola,Year,2022,320 000 [280 000 - 380 000]
2,HIV_0000000001,Estimated number of people (all ages) living w...,numeric,AFR,Africa,Country,AGO,Angola,Year,2021,320 000 [280 000 - 380 000]
3,HIV_0000000001,Estimated number of people (all ages) living w...,numeric,AFR,Africa,Country,AGO,Angola,Year,2020,320 000 [280 000 - 370 000]
4,HIV_0000000001,Estimated number of people (all ages) living w...,numeric,AFR,Africa,Country,AGO,Angola,Year,2015,300 000 [260 000 - 350 000]

In [17]:
#view the tail
df.tail()

,IndicatorCode,Indicator,ValueType,ParentLocationCode,ParentLocation,Location type,SpatialDimValueCode,Location,Period type,Period,Value
1547,HIV_0000000001,Estimated number of people (all ages) living w...,numeric,WPR,Western Pacific,Country,WSM,Samoa,Year,2020,No data
1548,HIV_0000000001,Estimated number of people (all ages) living w...,numeric,WPR,Western Pacific,Country,WSM,Samoa,Year,2015,No data
1549,HIV_0000000001,Estimated number of people (all ages) living w...,numeric,WPR,Western Pacific,Country,WSM,Samoa,Year,2010,No data
1550,HIV_0000000001,Estimated number of people (all ages) living w...,numeric,WPR,Western Pacific,Country,WSM,Samoa,Year,2005,No data
1551,HIV_0000000001,Estimated number of people (all ages) living w...,numeric,WPR,Western Pacific,Country,WSM,Samoa,Year,2000,No data

In [18]:
#get the shape of the dataset
df.shape

(1552, 11)

In [19]:
#get dataset info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1552 entries, 0 to 1551
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   IndicatorCode        1552 non-null   object
 1   Indicator            1552 non-null   object
 2   ValueType            1552 non-null   object
 3   ParentLocationCode   1552 non-null   object
 4   ParentLocation       1552 non-null   object
 5   Location type        1552 non-null   object
 6   SpatialDimValueCode  1552 non-null   object
 7   Location             1552 non-null   object
 8   Period type          1552 non-null   object
 9   Period               1552 non-null   int64
 10  Value                1552 non-null   object
dtypes: int64(1), object(10)
memory usage: 133.5+ KB

In [20]:
#get statistical summary
df.describe()

            Period
count  1552.000000
mean   2014.500000
std       8.080351
min    2000.000000
25%    2008.750000
50%    2017.500000
75%    2021.250000
max    2023.000000

In [22]:
#get statistical summary for categorical values
df.describe(include='O')

,IndicatorCode,Indicator,ValueType,ParentLocationCode,ParentLocation,Location type,SpatialDimValueCode,Location,Period type,Value
count,1552,1552,1552,1552,1552,1552,1552,1552,1552,1552
unique,1,1,1,6,6,1,194,194,1,895
top,HIV_0000000001,Estimated number of people (all ages) living w...,numeric,EUR,Europe,Country,AGO,Angola,Year,No data
freq,1552,1552,1552,424,424,1552,8,8,1552,394

## manipulating column names for better readability

In [23]:
#check column names
df.columns

Index(['IndicatorCode', 'Indicator', 'ValueType', 'ParentLocationCode',
       'ParentLocation', 'Location type', 'SpatialDimValueCode', 'Location',
       'Period type', 'Period', 'Value'],
      dtype='object')

In [25]:
#change column names to lowercase and replace spaces with underscores
df.columns = df.columns.str.lower().str.replace(' ', '_')
df.columns

Index(['indicatorcode', 'indicator', 'valuetype', 'parentlocationcode',
       'parentlocation', 'location_type', 'spatialdimvaluecode', 'location',
       'period_type', 'period', 'value'],
      dtype='object')

In [26]:
# dropping columns that we won't use
columns_to_drop = ['indicatorcode', 'indicator', 'valuetype', 'location_type', 'period_type']
df = df.drop(columns=columns_to_drop)
df.head()

,parentlocationcode,parentlocation,spatialdimvaluecode,location,period,value
0,AFR,Africa,AGO,Angola,2023,320 000 [280 000 - 380 000]
1,AFR,Africa,AGO,Angola,2022,320 000 [280 000 - 380 000]
2,AFR,Africa,AGO,Angola,2021,320 000 [280 000 - 380 000]
3,AFR,Africa,AGO,Angola,2020,320 000 [280 000 - 370 000]
4,AFR,Africa,AGO,Angola,2015,300 000 [260 000 - 350 000]

##Handle missing values